
# Types existant de NPC pour l'instant: 
# - SELLING

npcs:
  jhon:
    name: "Jhon"  # SANS COULEUR
    type: SELLING
    main-menu: apiarist_menu  # réfère aux fichiers dans menus/
  jean:
    name: "Jean"
    type: BUYING
    main-menu: golden_bourse
